//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public int ID { get; set; }
        public string Ciudad { get; set; }
        [MaxLength(50, ErrorMessage = "Está malo")] public string Direccion {get; set; }
        public int ID_Estado { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
